name: PazaBot NASA Daily Sender

on:
  schedule:
    # 10:00 UTC = 07:00 Horário de Brasília
    - cron: '0 10 * * *' 
  
  workflow_dispatch:

jobs:
  run-pazabot:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código (Checkout)
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Rodar o PazaBot
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_RECEIVERS: ${{ secrets.EMAIL_RECEIVERS }}
          APELIDO: ${{ secrets.APELIDO }}
          ASSINATURA: ${{ secrets.ASSINATURA }}
          GENAI_API_KEY: ${{ secrets.GENAI_API_KEY }}


        run: python main.py